/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ShopSlugRouteImport } from './routes/shop/$slug'
import { Route as RulesTermsRouteImport } from './routes/rules/terms'
import { Route as RulesPrivacyPolicyRouteImport } from './routes/rules/privacy-policy'
import { Route as RulesCookiesRouteImport } from './routes/rules/cookies'
import { Route as DashboardTestimonialsRouteImport } from './routes/dashboard/testimonials'
import { Route as DashboardSupportRouteImport } from './routes/dashboard/support'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as CategoriesSlugRouteImport } from './routes/categories/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as DashboardOrdersIndexRouteImport } from './routes/dashboard/orders/index'
import { Route as DashboardInventoryIndexRouteImport } from './routes/dashboard/inventory/index'
import { Route as DashboardCostumersIndexRouteImport } from './routes/dashboard/costumers/index'
import { Route as DashboardBlogIndexRouteImport } from './routes/dashboard/blog/index'
import { Route as DashboardAnalyticsIndexRouteImport } from './routes/dashboard/analytics/index'
import { Route as DashboardInventoryCreateRouteImport } from './routes/dashboard/inventory/create'
import { Route as DashboardInventoryCategoriesRouteImport } from './routes/dashboard/inventory/categories'
import { Route as DashboardInventoryIdRouteImport } from './routes/dashboard/inventory/$id'
import { Route as DashboardCostumersCostumersIdRouteImport } from './routes/dashboard/costumers/$costumersId'
import { Route as DashboardBlogCreateRouteImport } from './routes/dashboard/blog/create'
import { Route as DashboardBlogCategoriesRouteImport } from './routes/dashboard/blog/categories'
import { Route as DashboardBlogIdRouteImport } from './routes/dashboard/blog/$id'

const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesTermsRoute = RulesTermsRouteImport.update({
  id: '/rules/terms',
  path: '/rules/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesPrivacyPolicyRoute = RulesPrivacyPolicyRouteImport.update({
  id: '/rules/privacy-policy',
  path: '/rules/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesCookiesRoute = RulesCookiesRouteImport.update({
  id: '/rules/cookies',
  path: '/rules/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTestimonialsRoute = DashboardTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInventoryIndexRoute = DashboardInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCostumersIndexRoute = DashboardCostumersIndexRouteImport.update({
  id: '/costumers/',
  path: '/costumers/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBlogIndexRoute = DashboardBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnalyticsIndexRoute = DashboardAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInventoryCreateRoute =
  DashboardInventoryCreateRouteImport.update({
    id: '/inventory/create',
    path: '/inventory/create',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardInventoryCategoriesRoute =
  DashboardInventoryCategoriesRouteImport.update({
    id: '/inventory/categories',
    path: '/inventory/categories',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardInventoryIdRoute = DashboardInventoryIdRouteImport.update({
  id: '/inventory/$id',
  path: '/inventory/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCostumersCostumersIdRoute =
  DashboardCostumersCostumersIdRouteImport.update({
    id: '/costumers/$costumersId',
    path: '/costumers/$costumersId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBlogCreateRoute = DashboardBlogCreateRouteImport.update({
  id: '/blog/create',
  path: '/blog/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBlogCategoriesRoute = DashboardBlogCategoriesRouteImport.update({
  id: '/blog/categories',
  path: '/blog/categories',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBlogIdRoute = DashboardBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/help': typeof HelpRoute
  '/returns': typeof ReturnsRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/rules/cookies': typeof RulesCookiesRoute
  '/rules/privacy-policy': typeof RulesPrivacyPolicyRoute
  '/rules/terms': typeof RulesTermsRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/dashboard/blog/$id': typeof DashboardBlogIdRoute
  '/dashboard/blog/categories': typeof DashboardBlogCategoriesRoute
  '/dashboard/blog/create': typeof DashboardBlogCreateRoute
  '/dashboard/costumers/$costumersId': typeof DashboardCostumersCostumersIdRoute
  '/dashboard/inventory/$id': typeof DashboardInventoryIdRoute
  '/dashboard/inventory/categories': typeof DashboardInventoryCategoriesRoute
  '/dashboard/inventory/create': typeof DashboardInventoryCreateRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/blog/': typeof DashboardBlogIndexRoute
  '/dashboard/costumers/': typeof DashboardCostumersIndexRoute
  '/dashboard/inventory/': typeof DashboardInventoryIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/help': typeof HelpRoute
  '/returns': typeof ReturnsRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/rules/cookies': typeof RulesCookiesRoute
  '/rules/privacy-policy': typeof RulesPrivacyPolicyRoute
  '/rules/terms': typeof RulesTermsRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/blog': typeof BlogIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/shop': typeof ShopIndexRoute
  '/dashboard/blog/$id': typeof DashboardBlogIdRoute
  '/dashboard/blog/categories': typeof DashboardBlogCategoriesRoute
  '/dashboard/blog/create': typeof DashboardBlogCreateRoute
  '/dashboard/costumers/$costumersId': typeof DashboardCostumersCostumersIdRoute
  '/dashboard/inventory/$id': typeof DashboardInventoryIdRoute
  '/dashboard/inventory/categories': typeof DashboardInventoryCategoriesRoute
  '/dashboard/inventory/create': typeof DashboardInventoryCreateRoute
  '/dashboard/analytics': typeof DashboardAnalyticsIndexRoute
  '/dashboard/blog': typeof DashboardBlogIndexRoute
  '/dashboard/costumers': typeof DashboardCostumersIndexRoute
  '/dashboard/inventory': typeof DashboardInventoryIndexRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/help': typeof HelpRoute
  '/returns': typeof ReturnsRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsRoute
  '/rules/cookies': typeof RulesCookiesRoute
  '/rules/privacy-policy': typeof RulesPrivacyPolicyRoute
  '/rules/terms': typeof RulesTermsRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/dashboard/blog/$id': typeof DashboardBlogIdRoute
  '/dashboard/blog/categories': typeof DashboardBlogCategoriesRoute
  '/dashboard/blog/create': typeof DashboardBlogCreateRoute
  '/dashboard/costumers/$costumersId': typeof DashboardCostumersCostumersIdRoute
  '/dashboard/inventory/$id': typeof DashboardInventoryIdRoute
  '/dashboard/inventory/categories': typeof DashboardInventoryCategoriesRoute
  '/dashboard/inventory/create': typeof DashboardInventoryCreateRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/blog/': typeof DashboardBlogIndexRoute
  '/dashboard/costumers/': typeof DashboardCostumersIndexRoute
  '/dashboard/inventory/': typeof DashboardInventoryIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/cart'
    | '/contact'
    | '/deals'
    | '/help'
    | '/returns'
    | '/search'
    | '/shipping'
    | '/signin'
    | '/signup'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/testimonials'
    | '/rules/cookies'
    | '/rules/privacy-policy'
    | '/rules/terms'
    | '/shop/$slug'
    | '/blog/'
    | '/categories/'
    | '/dashboard/'
    | '/shop/'
    | '/dashboard/blog/$id'
    | '/dashboard/blog/categories'
    | '/dashboard/blog/create'
    | '/dashboard/costumers/$costumersId'
    | '/dashboard/inventory/$id'
    | '/dashboard/inventory/categories'
    | '/dashboard/inventory/create'
    | '/dashboard/analytics/'
    | '/dashboard/blog/'
    | '/dashboard/costumers/'
    | '/dashboard/inventory/'
    | '/dashboard/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/deals'
    | '/help'
    | '/returns'
    | '/search'
    | '/shipping'
    | '/signin'
    | '/signup'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/testimonials'
    | '/rules/cookies'
    | '/rules/privacy-policy'
    | '/rules/terms'
    | '/shop/$slug'
    | '/blog'
    | '/categories'
    | '/dashboard'
    | '/shop'
    | '/dashboard/blog/$id'
    | '/dashboard/blog/categories'
    | '/dashboard/blog/create'
    | '/dashboard/costumers/$costumersId'
    | '/dashboard/inventory/$id'
    | '/dashboard/inventory/categories'
    | '/dashboard/inventory/create'
    | '/dashboard/analytics'
    | '/dashboard/blog'
    | '/dashboard/costumers'
    | '/dashboard/inventory'
    | '/dashboard/orders'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/about'
    | '/cart'
    | '/contact'
    | '/deals'
    | '/help'
    | '/returns'
    | '/search'
    | '/shipping'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/testimonials'
    | '/rules/cookies'
    | '/rules/privacy-policy'
    | '/rules/terms'
    | '/shop/$slug'
    | '/blog/'
    | '/categories/'
    | '/dashboard/'
    | '/shop/'
    | '/dashboard/blog/$id'
    | '/dashboard/blog/categories'
    | '/dashboard/blog/create'
    | '/dashboard/costumers/$costumersId'
    | '/dashboard/inventory/$id'
    | '/dashboard/inventory/categories'
    | '/dashboard/inventory/create'
    | '/dashboard/analytics/'
    | '/dashboard/blog/'
    | '/dashboard/costumers/'
    | '/dashboard/inventory/'
    | '/dashboard/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  DealsRoute: typeof DealsRoute
  HelpRoute: typeof HelpRoute
  ReturnsRoute: typeof ReturnsRoute
  SearchRoute: typeof SearchRoute
  ShippingRoute: typeof ShippingRoute
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  RulesCookiesRoute: typeof RulesCookiesRoute
  RulesPrivacyPolicyRoute: typeof RulesPrivacyPolicyRoute
  RulesTermsRoute: typeof RulesTermsRoute
  ShopSlugRoute: typeof ShopSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/terms': {
      id: '/rules/terms'
      path: '/rules/terms'
      fullPath: '/rules/terms'
      preLoaderRoute: typeof RulesTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/privacy-policy': {
      id: '/rules/privacy-policy'
      path: '/rules/privacy-policy'
      fullPath: '/rules/privacy-policy'
      preLoaderRoute: typeof RulesPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/cookies': {
      id: '/rules/cookies'
      path: '/rules/cookies'
      fullPath: '/rules/cookies'
      preLoaderRoute: typeof RulesCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/testimonials': {
      id: '/dashboard/testimonials'
      path: '/testimonials'
      fullPath: '/dashboard/testimonials'
      preLoaderRoute: typeof DashboardTestimonialsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/inventory/': {
      id: '/dashboard/inventory/'
      path: '/inventory'
      fullPath: '/dashboard/inventory/'
      preLoaderRoute: typeof DashboardInventoryIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/costumers/': {
      id: '/dashboard/costumers/'
      path: '/costumers'
      fullPath: '/dashboard/costumers/'
      preLoaderRoute: typeof DashboardCostumersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/blog/': {
      id: '/dashboard/blog/'
      path: '/blog'
      fullPath: '/dashboard/blog/'
      preLoaderRoute: typeof DashboardBlogIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/analytics/': {
      id: '/dashboard/analytics/'
      path: '/analytics'
      fullPath: '/dashboard/analytics/'
      preLoaderRoute: typeof DashboardAnalyticsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/inventory/create': {
      id: '/dashboard/inventory/create'
      path: '/inventory/create'
      fullPath: '/dashboard/inventory/create'
      preLoaderRoute: typeof DashboardInventoryCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/inventory/categories': {
      id: '/dashboard/inventory/categories'
      path: '/inventory/categories'
      fullPath: '/dashboard/inventory/categories'
      preLoaderRoute: typeof DashboardInventoryCategoriesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/inventory/$id': {
      id: '/dashboard/inventory/$id'
      path: '/inventory/$id'
      fullPath: '/dashboard/inventory/$id'
      preLoaderRoute: typeof DashboardInventoryIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/costumers/$costumersId': {
      id: '/dashboard/costumers/$costumersId'
      path: '/costumers/$costumersId'
      fullPath: '/dashboard/costumers/$costumersId'
      preLoaderRoute: typeof DashboardCostumersCostumersIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/blog/create': {
      id: '/dashboard/blog/create'
      path: '/blog/create'
      fullPath: '/dashboard/blog/create'
      preLoaderRoute: typeof DashboardBlogCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/blog/categories': {
      id: '/dashboard/blog/categories'
      path: '/blog/categories'
      fullPath: '/dashboard/blog/categories'
      preLoaderRoute: typeof DashboardBlogCategoriesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/blog/$id': {
      id: '/dashboard/blog/$id'
      path: '/blog/$id'
      fullPath: '/dashboard/blog/$id'
      preLoaderRoute: typeof DashboardBlogIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardTestimonialsRoute: typeof DashboardTestimonialsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBlogIdRoute: typeof DashboardBlogIdRoute
  DashboardBlogCategoriesRoute: typeof DashboardBlogCategoriesRoute
  DashboardBlogCreateRoute: typeof DashboardBlogCreateRoute
  DashboardCostumersCostumersIdRoute: typeof DashboardCostumersCostumersIdRoute
  DashboardInventoryIdRoute: typeof DashboardInventoryIdRoute
  DashboardInventoryCategoriesRoute: typeof DashboardInventoryCategoriesRoute
  DashboardInventoryCreateRoute: typeof DashboardInventoryCreateRoute
  DashboardAnalyticsIndexRoute: typeof DashboardAnalyticsIndexRoute
  DashboardBlogIndexRoute: typeof DashboardBlogIndexRoute
  DashboardCostumersIndexRoute: typeof DashboardCostumersIndexRoute
  DashboardInventoryIndexRoute: typeof DashboardInventoryIndexRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardTestimonialsRoute: DashboardTestimonialsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBlogIdRoute: DashboardBlogIdRoute,
  DashboardBlogCategoriesRoute: DashboardBlogCategoriesRoute,
  DashboardBlogCreateRoute: DashboardBlogCreateRoute,
  DashboardCostumersCostumersIdRoute: DashboardCostumersCostumersIdRoute,
  DashboardInventoryIdRoute: DashboardInventoryIdRoute,
  DashboardInventoryCategoriesRoute: DashboardInventoryCategoriesRoute,
  DashboardInventoryCreateRoute: DashboardInventoryCreateRoute,
  DashboardAnalyticsIndexRoute: DashboardAnalyticsIndexRoute,
  DashboardBlogIndexRoute: DashboardBlogIndexRoute,
  DashboardCostumersIndexRoute: DashboardCostumersIndexRoute,
  DashboardInventoryIndexRoute: DashboardInventoryIndexRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  DealsRoute: DealsRoute,
  HelpRoute: HelpRoute,
  ReturnsRoute: ReturnsRoute,
  SearchRoute: SearchRoute,
  ShippingRoute: ShippingRoute,
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  RulesCookiesRoute: RulesCookiesRoute,
  RulesPrivacyPolicyRoute: RulesPrivacyPolicyRoute,
  RulesTermsRoute: RulesTermsRoute,
  ShopSlugRoute: ShopSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
